version: '2'
services:
    distributionnetwork_2017_05_30-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/DistributionNetwork_2017_05_30/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=DistributionNetwork_2017_05_30
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
